require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*

Rails:
  Enabled: true

Style/TrailingCommaInLiteral:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds.rb

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/Documentation:
  Enabled: false

# feature tests needs this
RSpec/ExampleLength:
  Exclude:
    - "spec/features/*_spec.rb"
