# Shared secrets are available across all environments.

shared:
  secret_key_base: b154dc29a23b8afb9ef85e94f8d3e1805dd982ec920fe1762086a9426c21f0f576d82a1344d5104c7280d7e1d158d232e929a3dfb83421e57cd1bfc0e8858030

  # default_url is required for links in email body or in links in controller
  # when url host is not available (for example rails console)
  default_url:
    host: <%= ENV['HOST'] || 'localhost' %>
    port: <%= ENV['PORT'] || '80' %>

development:
test:

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV.fetch "SECRET_KEY_BASE" %>
